# Generated by Django 5.2 on 2026-05-29 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_treatment', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('durasi', models.IntegerField(help_text='Durasi dalam menit')),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_reservasi', models.DateField()),
                ('jam_reservasi', models.TimeField()),
                ('waktu_pesan', models.DateTimeField(auto_now_add=True)),
                ('status_reservasi', models.CharField(choices=[('menunggu', 'Menunggu'), ('terkonfirmasi', 'Terkonfirmasi'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu', max_length=20)),
                ('nomor_antrian', models.IntegerField(blank=True, null=True)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.pelanggan')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.treatment')),
            ],
            options={
                'ordering': ['waktu_pesan'],
            },
        ),
    ]
