# Generated by Django 5.2 on 2026-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='treatments/'),
        ),
    ]
